[Tester]
; --- REQUIRED ---
Expert=EAV7.ex5
Symbol=XAUUSDr
Period=M15
Model=1
Deposit=10000
Leverage=1:10
ExecutionMode=0
Optimization=0
ShutdownTerminal=1

; --- WILL BE FILLED PER FOLD BY SCRIPT ---
FromDate=
ToDate=
Report=
ReplaceReport=1
ExpertParameters=
